### ISSUE TITLE
as_flextable() generic_labels argument ignored

### ISSUE THREAD

**Issue by technocrat** [DanChaltiel/crosstable#11]
```r
# from last example in as_flextable() documentation, changed from
# total = "Tot" to total = "Total
crosstable(mtcars2, -model, by=vs, total="both", test=TRUE, effect=TRUE) %>%
  rename(ID=.id, math=variable, Tot=Total, lab=label, pval=test, fx=effect) %>%
  as_flextable(by_header = "Engine shape", 
               generic_labels=list(id = "ID", variable = "math", total="Total", 
                                   label = "lab", test = "pval", effect="fx"))
```
produces the table shown in the attached screenshot, with the heading 'Tot', rather than the desired 'Total'

![image](https://user-images.githubusercontent.com/74648/159856534-dc5d037c-9f72-4473-95d0-c9fda07b6436.png)

Wonderful package. If necessary, I can run the html through a filter to get the presentation required.

**Comment by DanChaltiel** [comment]
Hi,
Thanks for the issue.

`generic_labels` is meant to tell `as_flextable()` that the columns are not named as they should have been.
Here, if you wrote `variable = "mathematics"`, it would fail because there is no column named "variable", and there is no column named "mathematics" either.
The column "total" is handled a bit differently so it won't fail, but the rule is the same.

If the desired heading is "Total", why did you rename it in the first place?

**Comment by DanChaltiel** [comment]
@technocrat if there is nothing more about this, I'll close the issue. Don't hesitate to reopen it if needed.
