### ISSUE TITLE
Issue installing the package on Mac

### ISSUE THREAD

**Issue by mkermanim** [DanChaltiel/crosstable#47]
I have the same issue that you mentioned in the package page. It says:
ERROR: failed to lock directory ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library’ for modifying
Try removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/00LOCK-flextable’

The downloaded source packages are in
	‘/private/var/folders/zh/sd5lrgn551x1jp3p7pzy1qz00000gp/T/RtmpDW8QTG/downloaded_packages’

**Comment by DanChaltiel** [comment]
Hi Hossein,
GitHub issues are usually for programmatical bugs caused by the package's code throwing an error, while you have an installation bug, which I cannot fix in any way.
Moreover, it is always a good practice to search for a solution for yourself before reaching out with a bug report on GitHub.
In your case, most R users have encountered this bug, so simply googling your error message "ERROR: failed to lock directory" will give you a vast amount of resources for installing a package and fixing eventual installation errors.
